# Generated by Django 5.0.6 on 2024-06-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderclone', '0003_user_profile_created_imagemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
