# Generated by Django 5.0.6 on 2024-06-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinderclone', '0004_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age',
            new_name='birthdate',
        ),
    ]
