# Generated by Django 5.0.6 on 2024-06-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderclone', '0005_rename_age_profile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='man', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.CharField(default='roommates', max_length=9),
        ),
    ]
