# Generated by Django 5.0.6 on 2024-07-02 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderclone', '0006_profile_gender_profile_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_2',
        ),
        migrations.AddField(
            model_name='conversation',
            name='profile_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to='tinderclone.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='profile_2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to='tinderclone.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=models.JSONField(default=list),
        ),
    ]
